#!/bin/bash



~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml

~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
~/Documents/BEAST/BEAST.v2.6.2.Linux/beast/bin/beast -overwrite out.xml
